### ISSUE TITLE
Pflegesterne Farbschema

### ISSUE THREAD

**Issue by LimNora** [Pflegesterne/frontend#10]
![farbschema](https://user-images.githubusercontent.com/47249813/84998710-782df800-b150-11ea-9fa8-fbb73bfaf886.png)

**Comment by kordianbruck** [comment]
Also ich weiß nicht wie gut das wirklich funktioniert:
![image](https://user-images.githubusercontent.com/298860/85236452-549fd180-b41e-11ea-9b95-47092bc0a6f6.png)

Gibts dazu noch mehr infos oder ist das alles?

**Comment by kordianbruck** [comment]
@michaelmischke gibts hier noch feedback?

**Comment by michaelmischke** [comment]
Alles gut soweit, bis ein richtiges design vorliegt ist das in Ordnung
