### ISSUE TITLE
IOS Web App (=Wrap-App?)

### ISSUE THREAD

**Issue by michaelmischke** [Pflegesterne/frontend#21]
- The service is available as an IOS Web App 
- The system should be able to sent full System notifications

**Comment by LimNora** [comment]
@michaelmischke only IOS? No android?

**Comment by JSchroeder-contec** [comment]
What is meant by system notifications?

**Comment by ConnyR** [comment]
approved :) very important :)

**Comment by mitunsleben** [comment]
Identisch zu [Issue 20](https://github.com/Pflegesterne/frontend/issues/20) für iOS-Geräte
