### ISSUE TITLE
Sorting of posts on Startscreen

### ISSUE THREAD

**Issue by michaelmischke** [Pflegesterne/frontend#25]
- [ ] As a user I can see "Newest", "Best" (most votes) and "Most comments" in the respective channels. E.g. as sorting options of my personal feed.

- [ ] As a user I have three buttons on the startscreen to change the selection
![Bildschirmfoto 2020-06-30 um 16 28 44](https://user-images.githubusercontent.com/66677543/86214604-a7def600-bb7b-11ea-859f-4da64ef95173.png)

**Comment by JSchroeder-contec** [comment]
approved

**Comment by ConnyR** [comment]
approved :)
