### ISSUE TITLE
design mainscreen 

### ISSUE THREAD

**Issue by michaelmischke** [Pflegesterne/frontend#26]
![Bildschirmfoto 2020-06-30 um 16 28 44](https://user-images.githubusercontent.com/66677543/86214828-fbe9da80-bb7b-11ea-8e4f-fa5ab3b3cef2.png)
![84996170-33549200-b14d-11ea-86ae-aa5c92d39622](https://user-images.githubusercontent.com/66677543/86214837-0015f800-bb7c-11ea-918d-5096a36e93ae.png)

**Comment by ConnyR** [comment]
approved
